name: .NET CI with Coverage

on:
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup .NET SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3. Install ReportGenerator tool
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # 4. Add .NET tools to PATH
      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # 5. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore "Backend/Backend.sln"

      # 6. Build the solution
      - name: Build
        run: dotnet build "Backend/Backend.sln"

      # 7. Ensure coverage folder exists
      - name: Ensure coverage folder exists
        run: mkdir -p Backend/BackendTests/coverage

      # 8. Run tests with coverage using coverlet.msbuild
      - name: Run tests with coverage
        working-directory: Backend/BackendTests
        run: |
          dotnet test BackendTests.csproj \
            /p:CollectCoverage=true \
            /p:CoverletOutput=coverage/coverage.xml \
            /p:CoverletOutputFormat=opencover

      # 9. Generate HTML coverage report
      - name: Generate HTML coverage report
        working-directory: Backend/BackendTests
        run: |
          reportgenerator \
            -reports:coverage/coverage.xml \
            -targetdir:coverage-report \
            -reporttypes:Html

      # 10. Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Backend/BackendTests/coverage-report
