name: feature-branch-unit-tests

on:
  push:
    branches:
      - "i*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup .NET SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore "Backend/Backend.sln"

      # 4. Build the solution
      - name: Build
        run: dotnet build "Backend/Backend.sln"

      # 5. Run unit tests only
      - name: Run unit tests
        working-directory: Backend/BackendTests
        run: |
          dotnet test BackendTests.csproj --filter "FullyQualifiedName~BackendTests.Unit"
